version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount the SQLite database file into the container
      - ./opti-campaign.db:/app/opti-campaign.db
    # Environment variables can be added here if needed
    # environment:
    #   - DATABASE_URL=sqlite:////app/sql_app.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
